version: 2
jobs:
  build:
    docker:
      - image: ubuntu:bionic-20180821
    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            mkdir artefacts
            ls
      - run:
          name: Run all
          command: |
            chmod +x scripts/run_all.sh
            sh scripts/run_all.sh v1.0.0 artefacts
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
