version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Prepare directory
          command: |
            mkdir artefacts
            ls
      - run:
          name: Build image from Dockerfile
          command: |
            docker build -t "ubit-upy-img" --build-arg VERSION=v1.0.0 . 2>&1 | tee artefacts/docker_build_op.txt
      - run:
          name: Save container artefacts
          command: |
            docker run --name ubit-upy-container ubit-upy-img
            docker cp ubit-upy-container:/home/artefacts .
      - run:
          name: Save docker image
          command: |
            docker save ubit-upy-img > ubit-upy-img.tar
            gzip -c ubit-upy-img.tar > ubit-upy-img.tar.gz
            mv ubit-upy-img.tar.gz artefacts/ubit-upy-img.tar.gz
      - store_artifacts:
          path: artefacts

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
